from __future__ import annotations

from futureos.config import settings
from futureos.llm import parse_with_ai
from futureos.models import Action, IntentType, Plan


def route(text: str) -> Plan:
    plan = _rule_first(text)
    if plan.actions:
        return plan
    if settings.use_ai_router:
        ai_plan = parse_with_ai(text)
        if ai_plan is not None:
            return ai_plan
    return Plan(
        original_text=text,
        actions=[Action(intent=IntentType.UNKNOWN, reason="No matching rule/parser")],
        needs_confirmation=False,
    )


def _rule_first(text: str) -> Plan:
    t = text.lower()
    actions: list[Action] = []
    target_path = "C:\\sample.txt" if any(k in t for k in ["o c", "ổ c", "c:\\"]) else "D:\\Study\\sample.txt"

    if any(k in t for k in ["ban thao", "draft", "tim file", "find file", "o d", "ổ d"]):
        actions.append(
            Action(
                intent=IntentType.FIND_DRAFT,
                args={"drive": "D:\\"},
                risk="low",
                reason="User asked to find draft/file in D drive",
            )
        )

    if any(k in t for k in ["doc file", "read file", "xem file"]):
        actions.append(
            Action(
                intent=IntentType.FILE_READ,
                args={"path": target_path},
                risk="low",
                reason="Requested file read",
            )
        )

    if any(k in t for k in ["ghi file", "write file", "cap nhat file", "cập nhật file"]):
        actions.append(
            Action(
                intent=IntentType.FILE_WRITE,
                args={"path": target_path, "content": "Updated by futureOS\n", "append": True},
                risk="medium",
                reason="Requested file write",
            )
        )

    if any(k in t for k in ["xoa file", "xoá file", "delete file"]):
        actions.append(
            Action(
                intent=IntentType.FILE_DELETE,
                args={"path": target_path},
                risk="high",
                reason="Requested file deletion",
            )
        )

    if "zalo" in t:
        actions.append(
            Action(
                intent=IntentType.SEND_ZALO,
                args={"recipient_hint": "boss", "message": "Auto message from futureOS"},
                risk="medium",
                reason="External channel send",
            )
        )

    if any(k in t for k in ["email hang loat", "email hàng loạt", "bulk email", "mail hang loat"]):
        actions.append(
            Action(
                intent=IntentType.SEND_BULK_EMAIL,
                args={
                    "subject": "Auto update",
                    "body": "Generated by futureOS",
                    "recipients": ["team@example.com"],
                },
                risk="high",
                reason="Bulk outbound action",
            )
        )

    needs_confirmation = any(a.risk in {"medium", "high"} for a in actions)
    if len(actions) > 1:
        return Plan(
            original_text=text,
            actions=[
                Action(intent=IntentType.COMPOSITE, args={"steps": [a.model_dump() for a in actions]}, risk="high")
            ],
            needs_confirmation=True,
        )
    return Plan(original_text=text, actions=actions, needs_confirmation=needs_confirmation)
